services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: comijest_backend
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      - MONGO_DB_CONNECTION_STRING=mongodb://mongo:27017/comijest
      - FLASK_ENV=production
      - JWT_SECRET="$UPER$EKRETNEKOD$$"
      - PYTHONUNBUFFERED=1
      - ADMIN_EMAIL=admin@comijest.pl
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=SuperBezpieczneHaslo!123
      - MODEL_DIR=/home/debian/comijest/backend/onedrive
      - MODEL_MAX_LENGTH=128
      - TRANSLATION_PROVIDER=libre
      - LIBRE_TRANSLATE_URL=http://libretranslate:5000/translate
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    networks:
      - comijest_net
    command: >
      sh -c "
      python app/scripts/create_admin.py &&
      gunicorn app:app --bind 0.0.0.0:5000
      "
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: comijest_frontend
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://comijest.pl/api
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - comijest_net

  nginx:
    image: nginx:1.29
    container_name: comijest_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
    networks:
      - comijest_net
    restart: unless-stopped
    
  mongo:
    image: mongo:8.2
    container_name: comijest_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - comijest_net
  
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - comijest_net

  libretranslate:
    image: libretranslate/libretranslate
    container_name: comijest_libretranslate
    restart: unless-stopped
    expose:
      - "5000"
    networks:
      - comijest_net

networks:
  comijest_net:
    driver: bridge

volumes:
  mongo_data:
